### ISSUE TITLE
delete old data

### ISSUE THREAD

**Issue by firefart** [ivre/ivre#1347]
Hi,
we are currently looking into deleting old data from our IVRE database and came across some limits. Currently we are importing a new nmap scan each month into the DB and now we want to get rid of everything that is older than 2 years.

We tried with the following but this has some inverted logic:
```
ivre scancli --timeago 63072000 --delete
ivre view --timeago 63072000 --delete
```

This is due to the `neg` parameter in `searchtimeago` beeing always `False` and thus always displaying results after the enddate.
https://github.com/ivre/ivre/blob/94215f62db2890144535d2c50e4774bd308f546f/ivre/db/__init__.py#L1946
https://github.com/ivre/ivre/blob/94215f62db2890144535d2c50e4774bd308f546f/ivre/db/mongo.py#L3021

Would it be possible to add a new cli parameter to those commands to also supply the `neg` parameter and search in the other direction?

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in IVRE and for this suggestion. What to you think of the proposal in #1348?

BTW, for similar use cases I tend to keep Nmap scans **but** to only build views using most recent scans (and I build a new view on a regular basis). The view is always "fresh", the history is kept in scans.

Hope this helps,

Pierre

**Comment by firefart** [comment]
Thanks for the quick fix @p-l- ! The PR looks good to me, that would work in our case.

We are not removing the view on each scan as we scan a lot of client PCs at different times which are not always online so we make use of the merge function of the view but we want to delete older data at some point.
Is there a programmatic way to delete the view before running `db2view` or does this need to be done directly in the DB? Could not find anything about this in the docs/

**Comment by p-l-** [comment]
What I usually do for such cases, is that I add a specific category for each scan, mentioning the date of the scan (e.g., `ivre scan2db -c CLIENTS,CLIENTS_20220512`); then, I create a new view (`ivre view --init`), and I build it with the results of the latest two (or three, or...) scans: `ivre db2view --no-merge nmap --category CLIENTS_20220512,CLIENTS_20220511`.

Would that work for you? Also, you can use different databases to store the different views, so that you still have a view "in production" when building the new one. For that, I have `DB_VIEW = "mongodb:///ivre_view_A"` in my configuration file, and to build the new view, I:
* create a file named `ivre_new_view.conf` containing `DB_VIEW = "mongodb:///ivre_view_B"`
* use `IVRE_CONF=ivre_new_view.conf ivre view --init`
* use `IVRE_CONF=ivre_new_view.conf ivre db2view --no-merge nmap --category CLIENTS_20220512,CLIENTS_20220511`

Let me know if you need me to clarify something.

**Comment by firefart** [comment]
btw: can you please push the updated images to dockerhub? (we are using the docker images)

**Comment by p-l-** [comment]
> btw: can you please push the updated images to dockerhub? (we are using the docker images)

Should be good now!

**Comment by p-l-** [comment]
>     * delete old scans

You may skip that step and use the scan collection as an archive, if you add a category indicating the date in your scan results, and use those categories to select the scan you want to use to create a view.
